### PR TITLE
Update for 1.2.4

### PR DESCRIPTION
**Pull request by ChrisBarker-NOAA**
Checklist
* [ x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x ] Bumped the build number (if the version is unchanged)
* [ x] Reset the build number to `0` (if the version changed)
* [ x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ChrisBarker-NOAA** [comment]
@conda-forge-admin, please rerender

**Comment by ChrisBarker-NOAA** [comment]
@ocefpaf: I'm confused about the "outputs" section here -- this is only one package, even though the source had multiple packages.

But git blame tells me that you added that this year, so maybe it has a purpose?

But the recipe as is seems to be building two packages, at least when I run conda build locally:

```
# To have conda build upload to anaconda.org automatically, use
# conda config --set anaconda_upload yes
anaconda upload \
    /Users/chris.barker/miniforge3/conda-bld/noarch/adios_db-1.2.4-py_0.tar.bz2 \
    /Users/chris.barker/miniforge3/conda-bld/noarch/adios-db-1.2.4-0.tar.bz2

```

help?

**Comment by ocefpaf** [comment]
The multiple outputs is used in that way to provide an alias for the `-` and `_` version of the package name. Conda-forge needs that to mimic PyPI's dash/underscore squashing.

**Comment by ChrisBarker-NOAA** [comment]
@thanks! I should have noticed that.

Boy, it would be nice to have a simpler way of doing that ...

**Pull request merged**
